baseURL = 'https://satsangee.org/'
title = 'Commonman Playbooks'
defaultContentLanguage = 'en'
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap']
enableRobotsTXT = false
[languages.en]
locale = 'en-GB'
contentDir = 'content/en'
weight = 1
[languages.or]
locale = 'or'
contentDir = 'content/or'
weight = 2
[languages.hi]
locale = 'hi'
contentDir = 'content/hi'
weight = 3
[markup.goldmark.renderer]
unsafe = false
[security.funcs]
getenv = ['^HUGO_', '^CI$', '^BUILD_COMMIT$', '^BUILD_DATE$']
